pipeline {
    agent any

    environment {
        TENANT_ID     = credentials('fabric-tenant-id')
        CLIENT_ID     = credentials('fabric-client-id')
        CLIENT_SECRET = credentials('fabric-client-secret')

        DEV_WORKSPACE_ID = "73997867-9f59-4ece-a5c4-b4cbde1a07e9"
        UAT_WORKSPACE_ID = "40c8fdea-6f13-4617-a454-1f39fb3ce2a4"
    }

    stages {

        stage('Get Access Token') {
            steps {
                script {
                    env.TOKEN = sh(
                        script: """
                        curl -s -X POST https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token \
                        -H "Content-Type: application/x-www-form-urlencoded" \
                        -d "grant_type=client_credentials" \
                        -d "client_id=${CLIENT_ID}" \
                        -d "client_secret=${CLIENT_SECRET}" \
                        -d "scope=https://analysis.windows.net/powerbi/api/.default" \
                        | jq -r .access_token
                        """,
                        returnStdout: true
                    ).trim()
                }
            }
        }

        stage('Export Report from DEV') {
            steps {
                sh """
                curl -L -X GET \
                "https://api.powerbi.com/v1.0/myorg/groups/${DEV_WORKSPACE_ID}/reports/5be0ebe8-e3c6-4e86-a678-81ede8e6f154/Export" \
                -H "Authorization: Bearer ${TOKEN}" \
                -o report.pbix
                """
            }
        }

        stage('Import into UAT') {
            steps {
                sh """
                curl -X POST \
                "https://api.powerbi.com/v1.0/myorg/groups/${UAT_WORKSPACE_ID}/imports?datasetDisplayName=uat-deploy&nameConflict=CreateOrOverwrite" \
                -H "Authorization: Bearer ${TOKEN}" \
                -F "file=@report.pbix"
                """
            }
        }

        stage('Refresh Dataset') {
            steps {
                sh """
                curl -X POST \
                "https://api.powerbi.com/v1.0/myorg/groups/${UAT_WORKSPACE_ID}/datasets/<UAT_DATASET_ID>/refreshes" \
                -H "Authorization: Bearer ${TOKEN}" \
                -H "Content-Type: application/json" \
                -d '{}'
                """
            }
        }
    }
}
